# Modified and stolen from Razgriz, who modified it from others.
# Builds and releases this package when the version number is changed.
name: Build Release

on:
  workflow_dispatch:

env:
  releasePrefix: "VRCBCE2"
  packageName: "com.vrcbilliards.vrcbce2"
  packagePath: "Packages/com.vrcbilliards.vrcbce2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version number from package manifest
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with:
          path: "./package.json"
          prop_path: "version"

      - name: Set Environment Variables to our target files
        run: |
          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV

      - name: Create directory and move files
        run: |
          mkdir -p ${{env.packagePath}}
          rsync -r --exclude="${{ env.packagePath }}" ./ "${{ env.packagePath }}"/

      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "${{ env.packagePath }}/"
          filename: "../../${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above

      - run: find "${{env.packagePath}}" -name \*.meta >> metaList

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          name: "${{ env.releasePrefix }} ${{ steps.version.outputs.prop }}"
          tag_name: ${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.unityPackage }}
            ./package.json
